[package]
name = "rust-axum-full-course"
version = "1.0.1"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }

# Serde / json
serde = { version = "1", features = ["derive"] }
serde_json = "1"


# Axum
axum = "0.6"

[dev-dependencies]
anyhow = "1"
httpc-test = "0.1.1"
